import pymongo
from pymongo import MongoClient
from settings import *


cluster = MongoClient(DATABASE)
db = cluster[DB_NAME]
collection = db[COLLECTION_NAME]

post = {
    "_id": 0,
    "cash_balances": {
        "Server_0": 10000,
        "Server_1": 10000,
        "Server_2": 10000,
    },
    "portfolios": {
        "Server_0": {
            "AAPL": 0,
            "MSFT": 0,
            "AMZN": 0,
            "GOOG": 0,
            "FB": 0,
            "TSLA": 0,
            "TSM": 0,
            "NVDA": 0,
            "PFE": 0,
            "T": 0,
            "ZM": 0,
            "AMD": 0,
            "BA": 0,
            "SQ": 0,
            "GE": 0,
            "ADSK": 0,
            "VRTX": 0,
            "PTON": 0,
            "NIO": 0,
            "F": 0,
            "CHWY": 0,
            "PLTR": 0,
            "NET": 0,
            "DKNG": 0,
            "FSLY": 0,
            "ARRY": 0,
            "HYLN": 0,
            "WKHS": 0,
        },
        "Server_1": {
            "AAPL": 0,
            "MSFT": 0,
            "AMZN": 0,
            "GOOG": 0,
            "FB": 0,
            "TSLA": 0,
            "TSM": 0,
            "NVDA": 0,
            "PFE": 0,
            "T": 0,
            "ZM": 0,
            "AMD": 0,
            "BA": 0,
            "SQ": 0,
            "GE": 0,
            "ADSK": 0,
            "VRTX": 0,
            "PTON": 0,
            "NIO": 0,
            "F": 0,
            "CHWY": 0,
            "PLTR": 0,
            "NET": 0,
            "DKNG": 0,
            "FSLY": 0,
            "ARRY": 0,
            "HYLN": 0,
            "WKHS": 0,
        },
        "Server_2": {
            "AAPL": 0,
            "MSFT": 0,
            "AMZN": 0,
            "GOOG": 0,
            "FB": 0,
            "TSLA": 0,
            "TSM": 0,
            "NVDA": 0,
            "PFE": 0,
            "T": 0,
            "ZM": 0,
            "AMD": 0,
            "BA": 0,
            "SQ": 0,
            "GE": 0,
            "ADSK": 0,
            "VRTX": 0,
            "PTON": 0,
            "NIO": 0,
            "F": 0,
            "CHWY": 0,
            "PLTR": 0,
            "NET": 0,
            "DKNG": 0,
            "FSLY": 0,
            "ARRY": 0,
            "HYLN": 0,
            "WKHS": 0,
        },


    },
}

collection.insert_one(post)
